<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Database\Seeder;

class BlogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Blog::create([

            'primary_image' => 'blog-img-1.png',
            'secondary_image' => 'blog-details1.png',

            'author_id' => 1,
            'category_id' => 1,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_1',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);
        Blog::create([

            'primary_image' => 'blog-img-2.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 1,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_2',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([

            'primary_image' => 'blog-img-3.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 1,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_3',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([

            'primary_image' => 'blog-img-1.png',
            'secondary_image' => 'blog-details1.png',

            'author_id' => 1,
            'category_id' => 1,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_4',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);
        Blog::create([

            'primary_image' => 'blog-img-2.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 2,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_5',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([

            'primary_image' => 'blog-img-3.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 2,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_6',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([

            'primary_image' => 'blog-img-3.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 2,
            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_7',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([

            'primary_image' => 'blog-img-2.png',
            'secondary_image' => 'blog-details2.png',

            'author_id' => 1,
            'category_id' => 2,

            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_8',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',


            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);

        Blog::create([
            'primary_image' => 'blog-img-1.png',
            'secondary_image' => 'blog-details1.png',

            'author_id' => 1,
            'category_id' => 2,

            'pl_title' => 'There are many variations of Traveling abroad will change you forever lost.',
            'slug' => 'there-are-many-variations-of_9',
            'sl_title' => 'Er zijn vele variaties vanto Traveling abroad will change you forever losting bekend gegeven.',

            'pl_description_pre_image' => 'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of 200 Latin words combined with a handful of sentence structure models to generate a Lorum Ipsum that appears reasonable. The generated Lorum Ipsum is therefore always free of repetition, injected humor or unusual words etc. to model sentence structure around one.<p>But I must explain to you how all this mistaken idea of ​​denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',
            'sl_description_pre_image' =>'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van 200 latijnse woorden gecombineerd met een handvol zinsstructuur modellen om een Lorum Ipsum te genereren die redelijk overkomt. De gegenereerde Lorum Ipsum is daardoor altijd vrij van herhaling, ingevoegde humor of ongebruikelijke woorden etc zinsstructuur modellen om een.<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes.</p>',

            'pl_description_post_image' =>'There are many variations of Lorem Ipsum passages available, but the majority have suffered from alterations in one form or another, from injected humor or randomly chosen words that do not seem half believable. If you are going to use a passage from Lorum Ipsum, make sure there is nothing embarrassing hidden in the middle of the text. All Lorum Ipsum generators on the Internet have the ability to repeat predefined parts where necessary so that this is the first real generator on the Internet. It uses a glossary of.',
            'sl_description_post_image' => 'Er zijn vele variaties van passages van Lorem Ipsum beschikbaar maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen. Als u een passage uit Lorum Ipsum gaat gebruiken dient u zich ervan te verzekeren dat er niets beschamends midden in de tekst verborgen zit. Alle Lorum Ipsum generators op Internet hebben de eigenschap voorgedefinieerde stukken te herhalen waar nodig zodat dit de eerste echte generator is op internet. Het gebruikt een woordenlijst van.',

            'active_status' => true,
            'popular' => true,
        ]);
    }
}
